<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" name="viewport"></meta>
<link href="../assets/img/professorctocat-git.svg" rel="shortcut icon" type="image/x-icon">
<link rel="stylesheet" href="../vendors/GainTime/version_0-1/assets/css/GainTime.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
