<?php
    session_start();
    require_once('../helpers/session.php');
    on();
    require_once('../models/users.php');
    $user = Users::select($_GET['id']);
?>
<!DOCTYPE html>
<html lang = "pt-br">
    <head>
        <?php include('includes/head.inc'); ?>
        <title>Edição de usuários</title>
    </head>
    <body>
        <?php include('includes/header.inc'); ?>
        <section class = "box last">
            <div class = "top-bar">
                <h2><i class = "fa fa-newspaper-o"></i> Editar Usuário</h2>
            </div>
            <?php $action = 'update'; ?>
            <?php include('includes/users-form.inc'); ?>
        </section>
		<?php include('includes/footer.inc'); ?>
        <script type = "text/javascript" src = "../vendors/jquery/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="../vendors/GainTime/version_0-1/assets/js/inputLabels.js"></script>
    </body>
</html>
