<?php session_start(); ?>
<?php require_once('../helpers/session.php'); ?>
<?php home(); ?>
<!DOCTYPE html>
<html>
    <head>
        <?php include('includes/head.inc'); ?>
        <title>Login</title>
    </head>
    <body>
        <section class="last login">
            <form action="../controllers/login.php" method="POST" class="s-form login-form">
                <a href="../"><img src="../assets/img/professorctocat-git.svg" alt="Professorctocat"></a>
                <div class="field has-label">
                    <label for="email">Email</label>
                    <input id="email" type="email" name="email" required="">
                </div>
                <div class="field has-label">
                    <label for="password">Senha</label>
                    <input id="password" type="password" name="password" required="">
                </div>
                <div class="forgot">
                    <a href="#">Esqueci minha senha.</a>
                </div>
                <button class="btn btn-principal" value="Entrar" id="submit_login"><i class="fa fa-sign-in"></i> Entrar</button>
            </form>
        </section>
        <?php include('includes/footer.inc'); ?>
    </body>
    <script type="text/javascript" src="../vendors/jquery/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="../vendors/GainTime/version_0-1/assets/js/inputLabels.js"></script>
</html>
